<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Borrow Records</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            margin: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #333;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f3f4f6;
            font-weight: bold;
        }
        h1 {
            text-align: center;
            margin-bottom: 30px;
        }
        .header {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
        }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
    </style>
</head>
<body>

    <div class="header">
        <div>
            <h2>AXIOM</h2>
            <p>Borrow Records Report</p>
        </div>
        <div class="text-right">
            <p><strong>Date:</strong> {{ now()->format('F d, Y h:i A') }}</p>
            <p><strong>Total Records:</strong> {{ $borrows->count() }}</p>
        </div>
    </div>

    <h1 class="text-center">Borrow Records</h1>

    @if($borrows->isEmpty())
        <p class="text-center">No borrow records found.</p>
    @else
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Book Title</th>
                    <th>Borrower</th>
                    <th>Requested At</th>
                    <th>Status</th>
                    @if($borrows->first()->due_date ?? false)
                        <th>Due Date</th>
                    @endif
                </tr>
            </thead>
            <tbody>
                @foreach($borrows as $key => $borrow)
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td>{{ $borrow->ebook->title ?? 'N/A' }}</td>
                    <td>{{ $borrow->user->full_name ?? 'N/A' }}</td>
                    <td>{{ $borrow->requested_at ? $borrow->requested_at->format('M d, Y') : 'N/A' }}</td>
                    <td>{{ ucfirst($borrow->status) }}</td>
                    @if($borrow->due_date ?? false)
                        <td>{{ $borrow->due_date->format('M d, Y') }}</td>
                    @endif
                </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div style="margin-top: 30px; text-align: center; font-size: 10px;">
        Generated by Axiom
    </div>

</body>
</html>
