<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Catalog Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 10px;
            margin: 24px;
            color: #1a1a2e;
        }

        /* ── Header ── */
        .report-header { width: 100%; margin-bottom: 6px; }
        .brand         { font-size: 17px; font-weight: bold; color: #1a1a2e; }
        .subtitle      { font-size: 9px; color: #5a5a7a; margin-top: 2px; }
        .meta          { font-size: 9px; color: #3a3a5a; line-height: 1.8; text-align: right; }
        .divider       { border: none; border-top: 2px solid #2a3050; margin: 8px 0 4px; }
        .report-title  { font-size: 14px; font-weight: bold; text-align: center; margin-bottom: 4px; }
        .report-note   { font-size: 9px; text-align: center; color: #8884a8; margin-bottom: 16px; }

        /* ── Summary box ── */
        .summary-table { width: 100%; border-collapse: collapse; margin-bottom: 18px; }
        .summary-table td {
            border: 1px solid #d8d6e8;
            padding: 7px 12px;
            text-align: center;
            width: 25%;
        }
        .summary-label { font-size: 8px; color: #8884a8; text-transform: uppercase; letter-spacing: 0.06em; display: block; margin-bottom: 3px; }
        .summary-value { font-size: 15px; font-weight: bold; color: #2a3050; }

        /* ── Category heading ── */
        .category-heading {
            background-color: #2a3050;
            color: white;
            font-size: 10px;
            font-weight: bold;
            padding: 6px 10px;
            margin-top: 14px;
            margin-bottom: 0;
            letter-spacing: 0.06em;
            text-transform: uppercase;
        }
        .category-subline {
            font-size: 8px;
            color: #5a5a7a;
            padding: 3px 10px 6px;
            border-left: 1px solid #d8d6e8;
            border-right: 1px solid #d8d6e8;
            background: #f7f7fb;
        }

        /* ── Book table ── */
        table.books {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 4px;
        }
        table.books th {
            background-color: #e8e8f0;
            border: 1px solid #d0cee8;
            padding: 5px 7px;
            font-size: 8.5px;
            font-weight: bold;
            color: #3a3a5a;
            text-align: left;
        }
        table.books td {
            border: 1px solid #e0def0;
            padding: 5px 7px;
            font-size: 9px;
            vertical-align: top;
        }
        table.books tbody tr:nth-child(even) { background-color: #faf9ff; }

        /* Stat cells */
        .stat       { text-align: center; font-weight: bold; }
        .stat-total { color: #2a3050; }
        .stat-active{ color: #1e8449; }
        .stat-done  { color: #8884a8; }
        .stat-cancel{ color: #c0392b; }

        /* Copies availability */
        .copies-ok  { color: #1e8449; font-weight: bold; }
        .copies-low { color: #b7600a; font-weight: bold; }
        .copies-none{ color: #c0392b; font-weight: bold; }

        /* ── Footer ── */
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 8.5px;
            color: #8884a8;
            border-top: 1px solid #e0def0;
            padding-top: 8px;
        }

        /* Page break between categories */
        .page-break { page-break-after: auto; }
    </style>
</head>
<body>

{{-- ── Report Header ── --}}
<table class="report-header" cellpadding="0" cellspacing="0">
    <tr>
        <td style="vertical-align:top; width:60%;">
            <div class="brand">AXIOM</div>
            <div class="subtitle">Library E-Resource Management System</div>
        </td>
        <td style="vertical-align:top; text-align:right;">
            <div class="meta">
                <strong>Date Generated:</strong> {{ now()->format('F d, Y g:i A') }}<br>
                <strong>Generated By:</strong> {{ $generatedBy }}<br>
                <strong>Total Categories:</strong> {{ $categories->count() }}<br>
                <strong>Total Books (borrowed):</strong> {{ $categories->sum(fn($c) => $c->books->count()) }}
            </div>
        </td>
    </tr>
</table>

<hr class="divider">
<div class="report-title">Book Catalog Report</div>
<div class="report-note">Only includes books that have at least one borrow record &nbsp;·&nbsp; Grouped by Category</div>

{{-- ── Summary Row ── --}}
@php
    $totalBorrows   = $categories->sum(fn($c) => $c->books->sum('all_borrows'));
    $totalActive    = $categories->sum(fn($c) => $c->books->sum('active_borrows'));
    $totalCompleted = $categories->sum(fn($c) => $c->books->sum('completed_borrows'));
    $totalCancelled = $categories->sum(fn($c) => $c->books->sum('cancelled_borrows'));
@endphp

<table class="summary-table">
    <tr>
        <td>
            <span class="summary-label">Total Borrow Records</span>
            <span class="summary-value">{{ $totalBorrows }}</span>
        </td>
        <td>
            <span class="summary-label">Currently Active</span>
            <span class="summary-value" style="color:#1e8449;">{{ $totalActive }}</span>
        </td>
        <td>
            <span class="summary-label">Completed (Expired)</span>
            <span class="summary-value" style="color:#8884a8;">{{ $totalCompleted }}</span>
        </td>
        <td>
            <span class="summary-label">Cancelled / Rejected</span>
            <span class="summary-value" style="color:#c0392b;">{{ $totalCancelled }}</span>
        </td>
    </tr>
</table>

{{-- ── Categories ── --}}
@forelse($categories as $category)
@php
    $catTotal     = $category->books->sum('all_borrows');
    $catActive    = $category->books->sum('active_borrows');
    $catCompleted = $category->books->sum('completed_borrows');
@endphp

<div class="category-heading">
    {{ $category->category_name }}
</div>
<div class="category-subline">
    {{ $category->books->count() }} book(s) &nbsp;·&nbsp;
    {{ $catTotal }} total borrow(s) &nbsp;·&nbsp;
    {{ $catActive }} currently active &nbsp;·&nbsp;
    {{ $catCompleted }} completed
</div>

<table class="books">
    <thead>
        <tr>
            <th style="width:3%;">#</th>
            <th style="width:26%;">Title</th>
            <th style="width:16%;">Author</th>
            <th style="width:8%;">Format</th>
            <th style="width:7%;">Copies</th>
            <th style="width:7%;">Available</th>
            <th style="width:8%;">Total Borrows</th>
            <th style="width:7%;">Active</th>
            <th style="width:7%;">Pending</th>
            <th style="width:8%;">Completed</th>
            <th style="width:8%;">Cancelled</th>
        </tr>
    </thead>
    <tbody>
        @foreach($category->books as $i => $book)
        @php
            $availRatio = $book->total_copies > 0
                ? $book->available_copies / $book->total_copies
                : 0;
            $copiesClass = $availRatio > 0.5
                ? 'copies-ok'
                : ($availRatio > 0 ? 'copies-low' : 'copies-none');
        @endphp
        <tr>
            <td class="stat">{{ $i + 1 }}</td>
            <td>{{ $book->title }}</td>
            <td>{{ $book->author->author_name ?? '—' }}</td>
            <td>{{ $book->format->format_type ?? '—' }}</td>
            <td class="stat">{{ $book->total_copies }}</td>
            <td class="stat {{ $copiesClass }}">{{ $book->available_copies }}</td>
            <td class="stat stat-total">{{ $book->all_borrows }}</td>
            <td class="stat stat-active">{{ $book->active_borrows }}</td>
            <td class="stat" style="color:#b7600a;">{{ $book->pending_borrows }}</td>
            <td class="stat stat-done">{{ $book->completed_borrows }}</td>
            <td class="stat stat-cancel">{{ $book->cancelled_borrows }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

@empty
    <p style="text-align:center;color:#8884a8;margin-top:30px;">
        No books with borrow records found.
    </p>
@endforelse

<div class="footer">
    Generated by AXIOM Library E-Resource Management System
    &nbsp;·&nbsp; {{ now()->format('F d, Y') }}
    &nbsp;·&nbsp; Confidential — For Library Use Only
</div>

</body>
</html>